#!/bin/bash
#SBATCH --job-name=job8f7dcfc507914a154a5bbc7d03893c31
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1536724028/logs/job8f7dcfc507914a154a5bbc7d03893c31.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1536724028/logs/job8f7dcfc507914a154a5bbc7d03893c31.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1536724028/jobs/job8f7dcfc507914a154a5bbc7d03893c31.rds)"
