#!/bin/bash
#SBATCH --job-name=job82c9f83cc5c6e411ec19d02782e7b702
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_404062394/logs/job82c9f83cc5c6e411ec19d02782e7b702.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_404062394/logs/job82c9f83cc5c6e411ec19d02782e7b702.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_404062394/jobs/job82c9f83cc5c6e411ec19d02782e7b702.rds)"
