#!/bin/bash
#SBATCH --job-name=jobafad3ee2be52df7b562bd13237bc83d1
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1250635330/logs/jobafad3ee2be52df7b562bd13237bc83d1.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1250635330/logs/jobafad3ee2be52df7b562bd13237bc83d1.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1250635330/jobs/jobafad3ee2be52df7b562bd13237bc83d1.rds)"
