#!/bin/bash
#SBATCH --job-name=jobde0d306921419dfbf8e0d915d1f18bfe
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_464765635/logs/jobde0d306921419dfbf8e0d915d1f18bfe.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_464765635/logs/jobde0d306921419dfbf8e0d915d1f18bfe.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_464765635/jobs/jobde0d306921419dfbf8e0d915d1f18bfe.rds")'