#!/bin/bash
#SBATCH --job-name=job588a045d6cedfce7e494778bbbdc8ec8
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_911234345/logs/job588a045d6cedfce7e494778bbbdc8ec8.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_911234345/logs/job588a045d6cedfce7e494778bbbdc8ec8.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
