#!/bin/bash
#SBATCH --job-name=jobc1438830d498589dbb8df86895c9adde
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_292618632/logs/jobc1438830d498589dbb8df86895c9adde.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_292618632/logs/jobc1438830d498589dbb8df86895c9adde.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_292618632/jobs/jobc1438830d498589dbb8df86895c9adde.rds)"
