#!/bin/bash
#SBATCH --job-name=job2e90eb82a660109a398ea2b73dfdc3ce
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1567078427/logs/job2e90eb82a660109a398ea2b73dfdc3ce.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1567078427/logs/job2e90eb82a660109a398ea2b73dfdc3ce.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(", uri, ")"
