#!/bin/bash
#SBATCH --job-name=job358d5c3cfa0c00f5bec1f30e1ea8408d
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1441193705/logs/job358d5c3cfa0c00f5bec1f30e1ea8408d.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1441193705/logs/job358d5c3cfa0c00f5bec1f30e1ea8408d.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1441193705/jobs/job358d5c3cfa0c00f5bec1f30e1ea8408d.rds)"
