#!/bin/bash
#SBATCH --job-name=jobfa54cff05ddf1277874531bbacb1a348
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_43037697/logs/jobfa54cff05ddf1277874531bbacb1a348.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_43037697/logs/jobfa54cff05ddf1277874531bbacb1a348.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_43037697/jobs/jobfa54cff05ddf1277874531bbacb1a348.rds")'