#!/bin/bash
#SBATCH --job-name=jobb4f334d78eccdcf457ec03451b35a145
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1010188553/logs/jobb4f334d78eccdcf457ec03451b35a145.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1010188553/logs/jobb4f334d78eccdcf457ec03451b35a145.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(", uri, ")"
