#!/bin/bash
#SBATCH --job-name=job8fb92046eb5b0e5c2dae556ac9630552
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_96864048/logs/job8fb92046eb5b0e5c2dae556ac9630552.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_96864048/logs/job8fb92046eb5b0e5c2dae556ac9630552.log
#SBATCH --time=
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
Rscript -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_96864048/jobs/job8fb92046eb5b0e5c2dae556ac9630552.rds")'
