#!/bin/bash
#SBATCH --job-name=jobbb691a4145be2ad0a18e2f737b1363da
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_223493310/logs/jobbb691a4145be2ad0a18e2f737b1363da.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_223493310/logs/jobbb691a4145be2ad0a18e2f737b1363da.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_223493310/jobs/jobbb691a4145be2ad0a18e2f737b1363da.rds)"
