#!/bin/bash
#SBATCH --job-name=job25c2ac55a8a2f2b82dc64a3ee5d9b2c1
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_905834892/logs/job25c2ac55a8a2f2b82dc64a3ee5d9b2c1.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_905834892/logs/job25c2ac55a8a2f2b82dc64a3ee5d9b2c1.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_905834892/jobs/job25c2ac55a8a2f2b82dc64a3ee5d9b2c1.rds")'