#!/bin/bash
#SBATCH --job-name=jobf8d389a0d693a71866db9f5cae94f035
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_381422337/logs/jobf8d389a0d693a71866db9f5cae94f035.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_381422337/logs/jobf8d389a0d693a71866db9f5cae94f035.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_381422337/jobs/jobf8d389a0d693a71866db9f5cae94f035.rds")'