#!/bin/bash
#SBATCH --job-name=jobf0c8d523acc45d62d6f50a54c1bfadae
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1075123281/logs/jobf0c8d523acc45d62d6f50a54c1bfadae.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1075123281/logs/jobf0c8d523acc45d62d6f50a54c1bfadae.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1075123281/jobs/jobf0c8d523acc45d62d6f50a54c1bfadae.rds)"
