#!/bin/bash
#SBATCH --job-name=job98a3538f4fd1d5302613127bdbd7fd9c
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1473494440/logs/job98a3538f4fd1d5302613127bdbd7fd9c.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1473494440/logs/job98a3538f4fd1d5302613127bdbd7fd9c.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


/home/baker02/miniconda3/envs/perturbverse/bin/Rscript -e "batchtools::doJobCollection(/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_134457-zPbEXR/batchtools_1473494440/jobs/job98a3538f4fd1d5302613127bdbd7fd9c.rds)"
