#!/bin/bash
#SBATCH --job-name=jobb6e83afe34a99b9613a3d6e23af0f8e1
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_61726978/logs/jobb6e83afe34a99b9613a3d6e23af0f8e1.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_61726978/logs/jobb6e83afe34a99b9613a3d6e23af0f8e1.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_61726978/jobs/jobb6e83afe34a99b9613a3d6e23af0f8e1.rds")'