#!/bin/bash
#SBATCH --job-name=jobe3643c986ed9b5e26e1bbf685a76b7d8
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_1703105263/logs/jobe3643c986ed9b5e26e1bbf685a76b7d8.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_1703105263/logs/jobe3643c986ed9b5e26e1bbf685a76b7d8.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_114538-vregcp/batchtools_1703105263/jobs/jobe3643c986ed9b5e26e1bbf685a76b7d8.rds")'