#!/bin/bash
#SBATCH --job-name=jobba828cc27518a85d6f6a9487bbaaed4a
#SBATCH --output=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_2100634889/logs/jobba828cc27518a85d6f6a9487bbaaed4a.log
#SBATCH --error=/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_2100634889/logs/jobba828cc27518a85d6f6a9487bbaaed4a.log
#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2G


export DEBUGME=
source activate perturbverse
0 -e 'batchtools::doJobCollection("/mnt/scratcha/fmlab/baker02/crigen/notebooks/.future/20210721_115244-ffQVNo/batchtools_2100634889/jobs/jobba828cc27518a85d6f6a9487bbaaed4a.rds")'